### ISSUE TITLE
Add option in settings to pass command line flags to DCMTK tools

### ISSUE THREAD

**Issue by fedorov** [QIICR/atom-dicom-dump#4]
suggested by @jriesmeier

**Comment by jriesmeier** [comment]
Thanks for your quick implementation! It works... but for a single option (e.g. "-M") only. If I specify multiple options (e.g. "-M -L"), the output window is empty. Could be a quoting issue, i.e. a problem with " around the options.

**Comment by fedorov** [comment]
Thanks for letting me know! This should be fixed in 0.2.10 by this commit: https://github.com/QIICR/atom-dicom-dump/commit/25d822e92f6a171d6470827d59abdbe648d1f522. The problem was that each flag should be passed as a separate item in the arguments array.

I also added clarification to the config options that no quotes around the command line flags should be used.

**Comment by jriesmeier** [comment]
I can confirm that it works now with more than a single option, e.g. with "-M -L" (see above). This is at least true as long as no quotation marks are used (e.g. as required for option values that contain spaces or other special characters), but as you've documented: "no quotes!" ;-)

Also thank you for changing the order of the input fields. This is something that I also observed for the previous version/release (but forgot to mention).

**Comment by fedorov** [comment]
> as long as no quotation marks are used (e.g. as required for option values that contain spaces or other special characters)

If you have some arguments that need to be passed to a certain flag, I should be able to make it work by improving the robustness of the flags parsing. Right now I just split by space the text passed by the user. If you believe it is important to be able to pass flag options and they may contain spaces (i.e., those flags and options are really useful in this context), can you please add example to this issue?

> Also thank you for changing the order of the input fields

I noticed it earlier too, and was annoyed about it, but could not quickly find documentation how to specify the order (default is sort alphabetically). This time I was more successful! :)

**Comment by jriesmeier** [comment]
I think for dcmdump and dsrdump there is no _good_ example why quotation marks (for escaping spaces or other special characters) would be needed. So, it probably makes no sense to invest this extra time. It might be different for other DCMTK tools...
