### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by bcli4d** [QIICR/atom-dicom-dump#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [dicom-dump](https://github.com/QIICR/atom-dicom-dump) package 0.2.10

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/BillClifford/.atom/packages/dicom-dump/lib/dicom-dump.coffee:70

TypeError: Cannot read property 'getPath' of undefined
    at Object.dcmdumpView (/packages/dicom-dump/lib/dicom-dump.coffee:70:52)
    at /packages/dicom-dump/lib/dicom-dump.coffee:50:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1300:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:57.5.0 core:delete (input.hidden-input)
     -8:55.3.0 core:paste (input.hidden-input)
 70x -8:51.6.0 core:move-left (input.hidden-input)
     -7:06.6.0 application:open (div.panels-item)
  2x -5:14.5.0 dicom-dump:toggledcm (input.hidden-input)
     -2:35.8.0 core:paste (input.hidden-input)
     -2:30.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:12.7.0 dicom-dump:toggledcm (div.tool-panel.tree-view)
     -1:28 application:open (div.tool-panel.tree-view)
     -0:33.2.0 dicom-dump:toggledcm (input.hidden-input)
     -0:22.3.0 dicom-dump:togglesr (input.hidden-input)
     -0:07.7.0 dicom-dump:toggledcm (div.tool-panel.tree-view)
```

### Non-Core Packages

```
dicom-dump 0.2.10 
```

**Comment by bcli4d** [comment]
Tried with dcmdump in 3dSlicer installation and dcmdump from Atom package installer.

**Comment by fedorov** [comment]
How did you trigger dcmdump? Did you have a DICOM file open in the editor at the time you called it?

**Comment by bcli4d** [comment]
Yes. I opened the file and then clicked on Packages->dicom-dump->Toggle
dcmdump.

Bill

**Comment by fedorov** [comment]
Is the file you are opening on a local file system or somewhere else? Can you test by copying the file to your home directory and opening it from there? I have a mac, and I used it with the dcmdump from 3D Slicer, and I never had this problem. We need to debug what is special for your system and/or that file!

**Comment by bcli4d** [comment]
I get the same error when the file is in ~. The files are local; and I've
tried several. These are files that I downloaded from TCIA. Downloaded six
months ago, but no reason why they shouldn't still be good.

I'll try uninstalling/reinstalling Atom, etc. and let you know what I find.

Bill

**Comment by bcli4d** [comment]
My fault: In settings, I'd set the Path to dcmdump rather than the
directory containing dcmdump. It's working now after restarting Atom.

**Comment by fedorov** [comment]
Ahh, ok! Still, the location of error does not make sense to me. But this is a good feedback. I should add a check that dcmdump exists before trying to call it.
