### ISSUE TITLE
Consider integration with gdcmdump

### ISSUE THREAD

**Issue by fedorov** [QIICR/atom-dicom-dump#8]
`gdcmdump` provides functionality not available in `dcmdump`, such as Siemens header parsing, so it might be quite helpful to add it.

@malaterre - would you be by any chance interested to contribute this functionality? Any thoughts are welcome!

**Comment by malaterre** [comment]
@fedorov Like what ? The code is released as BSD within GDCM ? Do you want me to submit a PR to dcmtk folks ?

**Comment by fedorov** [comment]
Sorry for the confusion ...

This is purely in the context of this specific package for the Atom editor. In a nutshell, it currently provides interface to the dcmdump and dsrdump tools of DCMTK (see description here: https://github.com/QIICR/atom-dicom-dump). What I was suggesting to also add a wrapper for gdcmdump. It is rather easy on its own, but I thought I make you aware of this package, and see if you are interested to use/contribute.
